package com.ascent.bean;

/**
 * Product generated by MyEclipse Persistence Tools
 */

public class Product2 implements java.io.Serializable {

	// Fields

	private Integer pid;

	private String productId;

	private String productname;

	private String author;

	private String publisher;


	private String price1;

	private String price2;

	private String category;
	
	private String image;
	
	private String bigimage;
	
	private String number;
	
	private String note;
	
	private Integer newproduct;
	
	private String realstock;
	
	private String stock;//库存

	private Integer delFlag;

	private String temp1;

	private String temp2;

	private String temp3;

	private String temp4;
	
	//临时加质量字段
	private String quantity;
	

	// Constructors

	

	/** default constructor */
	public Product2() {
	}


	public String getAuthor() {
		return author;
	}


	public void setAuthor(String author) {
		this.author = author;
	}


	public String getBigimage() {
		return bigimage;
	}


	public void setBigimage(String bigimage) {
		this.bigimage = bigimage;
	}


	public String getCategory() {
		return category;
	}


	public void setCategory(String category) {
		this.category = category;
	}


	public Integer getDelFlag() {
		return delFlag;
	}


	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}


	public String getImage() {
		return image;
	}


	public void setImage(String image) {
		this.image = image;
	}


	public Integer getNewproduct() {
		return newproduct;
	}


	public void setNewproduct(Integer newproduct) {
		this.newproduct = newproduct;
	}


	public String getNote() {
		return note;
	}


	public void setNote(String note) {
		this.note = note;
	}


	public String getNumber() {
		return number;
	}


	public void setNumber(String number) {
		this.number = number;
	}


	public Integer getPid() {
		return pid;
	}


	public void setPid(Integer pid) {
		this.pid = pid;
	}


	public String getPrice1() {
		return price1;
	}


	public void setPrice1(String price1) {
		this.price1 = price1;
	}


	public String getPrice2() {
		return price2;
	}


	public void setPrice2(String price2) {
		this.price2 = price2;
	}


	public String getProductId() {
		return productId;
	}


	public void setProductId(String productId) {
		this.productId = productId;
	}


	public String getProductname() {
		return productname;
	}


	public void setProductname(String productname) {
		this.productname = productname;
	}


	public String getPublisher() {
		return publisher;
	}


	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}


	public String getQuantity() {
		return quantity;
	}


	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}


	public String getRealstock() {
		return realstock;
	}


	public void setRealstock(String realstock) {
		this.realstock = realstock;
	}


	public String getStock() {
		return stock;
	}


	public void setStock(String stock) {
		this.stock = stock;
	}


	public String getTemp1() {
		return temp1;
	}


	public void setTemp1(String temp1) {
		this.temp1 = temp1;
	}


	public String getTemp2() {
		return temp2;
	}


	public void setTemp2(String temp2) {
		this.temp2 = temp2;
	}


	public String getTemp3() {
		return temp3;
	}


	public void setTemp3(String temp3) {
		this.temp3 = temp3;
	}


	public String getTemp4() {
		return temp4;
	}


	public void setTemp4(String temp4) {
		this.temp4 = temp4;
	}


	
	
}